// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Dropdown_Countries', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Dropdown_Countries', async function() {
    // Test name: Dropdown_Countries
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/ | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1552x849 | 
    await driver.manage().window().setRect(1552, 849)
    // 3 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 4 | click | css=.selectDiv:nth-child(1) .tester | 
    await driver.findElement(By.css(".selectDiv:nth-child(1) .tester")).click()
    // 5 | select | css=.selectDiv:nth-child(1) .tester | label=Dominican Republic
    {
      const dropdown = await driver.findElement(By.css(".selectDiv:nth-child(1) .tester"))
      await dropdown.findElement(By.xpath("//option[. = 'Dominican Republic']")).click()
    }
    // 6 | click | css=.selectDiv:nth-child(1) .tester | 
    await driver.findElement(By.css(".selectDiv:nth-child(1) .tester")).click()
  })
})
