// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Navbar_Redirection', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Navbar_Redirection', async function() {
    // Test name: Navbar_Redirection
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/ | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1552x849 | 
    await driver.manage().window().setRect(1552, 849)
    // 3 | click | linkText=Graphs | 
    await driver.findElement(By.linkText("Graphs")).click()
    // 4 | click | linkText=Report | 
    await driver.findElement(By.linkText("Report")).click()
    // 5 | click | linkText=References | 
    await driver.findElement(By.linkText("References")).click()
    // 6 | click | linkText=Contact us | 
    await driver.findElement(By.linkText("Contact us")).click()
  })
})
