// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Record_Write_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Record_Write_Test', async function() {
    // Test name: Record_Write_Test
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/ | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1552x849 | 
    await driver.manage().window().setRect(1552, 849)
    // 3 | click | css=.textAreaRep | 
    await driver.findElement(By.css(".textAreaRep")).click()
    // 4 | type | css=.textAreaRep | This is a test
    await driver.findElement(By.css(".textAreaRep")).sendKeys("This is a test")
    // 5 | click | css=.submitButton | 
    await driver.findElement(By.css(".submitButton")).click()
  })
})
