// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Sort_Confirmed_Deaths_Recovered', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Sort_Confirmed_Deaths_Recovered', async function() {
    // Test name: Sort_Confirmed_Deaths_Recovered
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/ | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1552x849 | 
    await driver.manage().window().setRect(1552, 849)
    // 3 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 4 | click | css=#column-confirmed > div | 
    await driver.findElement(By.css("#column-confirmed > div")).click()
    // 5 | click | css=.iQWYOm | 
    await driver.findElement(By.css(".iQWYOm")).click()
    // 6 | click | css=#column-deaths > .sc-kEqXSa | 
    await driver.findElement(By.css("#column-deaths > .sc-kEqXSa")).click()
    // 7 | click | css=.eQoFRX | 
    await driver.findElement(By.css(".eQoFRX")).click()
    // 8 | click | css=#column-recovered > div | 
    await driver.findElement(By.css("#column-recovered > div")).click()
    // 9 | click | css=#column-recovered > div | 
    await driver.findElement(By.css("#column-recovered > div")).click()
  })
})
