// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Sort_Table_Countries', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Sort_Table_Countries', async function() {
    // Test name: Sort_Table_Countries
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/ | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1552x849 | 
    await driver.manage().window().setRect(1552, 849)
    // 3 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 4 | click | css=.sc-kEqXSa:nth-child(2) | 
    await driver.findElement(By.css(".sc-kEqXSa:nth-child(2)")).click()
    // 5 | click | css=.iQWYOm | 
    await driver.findElement(By.css(".iQWYOm")).click()
    // 6 | click | css=.eQoFRX | 
    await driver.findElement(By.css(".eQoFRX")).click()
  })
})
